import type { Metadata } from "next";
import { PT_Serif } from "next/font/google";
import "./globals.css";
import Navbar from "./(layout)/Navbar";
import Footer from "./(layout)/Footer";

const ptSerif = PT_Serif({ subsets: ["latin"], weight: ["400", "700"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

type RootLayoutProps = {
	children: React.ReactNode;
};

export default function RootLayout({ children }: RootLayoutProps) {
	return (
		<html lang="en">
			<body className={ptSerif.className}>
				<Navbar />
				{children}
				<Footer />
			</body>
		</html>
	);
}
